package-lock.json, package.json, src/index.js
set up basic router
added TODO for mobile
=> adding router

package-lock.json, package.json, src/Enums.js, src/FirebaseConfig.js, src/PageContainer.js, src/PageContent/RequestPickup/PickupSummary.js, src/PageContent/RequestPickup/RecurringPickupRequest.js, src/Utils.js, src/schema.txt
Trello task: https://trello.com/c/Lbc7PzNr/24-delivery-backend-1-recurring-pickup-request
**Step 1 in pickup request backend: write request to database.**
**Changes:**
- `PageContainer`: query for the `DonatingAgency` object from DB if the user logged in is `DonatingAgencyMember`
- `RecurringPickupRequest`:
- fill in code to query all DA members, RAs, and DGs from DB to populate the dropdown lists
- create `DeliveryRequest` object and write to DB
- Other minor changes:
- added `moment` module
- move getting weekday from date to a utils file
- make repeats & primary contact dropdown lists required in the form
- minor fixes and style changes
**Test:** tested by creating requests through UI and examine the database
**TODOs:**
- Populate `PickupSummary` with data from db
- Add some sort of …
=> [Backend] Pickup Request Step 1

.gitignore, src/PageContainer.js, src/PageContent/Calendar/Content.css, src/PageContent/Calendar/Dialog.js, src/PageContent/Calendar/DialogContent.js, src/PageContent/Calendar/DonatingAgencyContent.js
Reverts huangjoyce3/MealMatch#44
=> Revert "Revert "[Calendar] Dining hall content""

src/SignUpIn/DelivererGroup/DelivererGroupSignUp2.js, src/SignUpIn/DelivererGroup/DelivererGroupSignUpController.js, src/SignUpIn/DonatingAgency/DonatingAgencySignUp2.js, src/SignUpIn/DonatingAgency/DonatingAgencySignUpController.js, src/SignUpIn/ReceivingAgency/ReceivingAgencySignUp2.js, src/SignUpIn/ReceivingAgency/ReceivingAgencySignUp4.js, src/SignUpIn/ReceivingAgency/ReceivingAgencySignUpController.js, src/SignUpIn/SignUpComplete.js, src/SignUpIn/SignUpIn.css
- show firebase's error message when sign up failed
- compare password on both changes
- try different bad sign up info cases with all 3 account types
- make sure good ones still work
=> show sign up error

src/PageContent/AssignVolunteers/Edit.js, src/PageContent/Calendar/ContactContent.js, src/PageContent/Calendar/DelivererGroupContent.js, src/PageLayout/Notification/Recurring/EnterPrimaryContact.js, src/SignUpIn/DelivererGroup/DelivererGroupSignUp2.js, src/SignUpIn/DonatingAgency/DonatingAgencyMemberSignup.js, src/SignUpIn/DonatingAgency/DonatingAgencySignUp2.js, src/SignUpIn/ReceivingAgency/ReceivingAgencySignUp4.js
Added John's phone util everywhere.
=> Phone util

src/Enums.js, src/SignUpIn/DelivererGroup/DelivererGroupSignUpController.js, src/SignUpIn/DonatingAgency/DonatingAgencySignUpController.js, src/SignUpIn/ReceivingAgency/ReceivingAgencySignUpController.js
- created email: mealmatch.uw@gmail.com
- created an umbrella account in db for production use
- changed code to create accounts under this new umbrella
Created test accounts, make sure it got added to the new UW umbrella correctly. (Removed them after testing)
=> [production] UW Umbrella Account

src/SignUpIn/SignUpIn.css
- Feedback from user: input width too small
=> time input width

firebase.json
Reverts huangjoyce3/MealMatch#66
=> Revert "cache settings"

firebase.json
Reverts huangjoyce3/MealMatch#74
=> Revert "Revert "cache settings""

.gitignore
UI fixes:
- remove detailed error message
=> Release-1.0.2

dev_deploy
script for deploying to `development`
=> [tools] DEV deploy script

src/Map/Map.js
fixed undefined longitude value
add link on desktop view
=> [Hotfix] mobile map link

src/Map/Map.js, src/Map/Marker.css
=> [hotfix] fix link for iOS, desktop font size

src/PageLayout/Notification/Details/RequestSummary.js
=> Release 1.2.2

src/PageContainer.js
Fixed page title to show agency name for DA Members rather than the member's name...
=> PageHeader |  Fix Page Title

src/PageLayout/PageHeader.css
Hotfix PageHeader styles regression introduced by previous commits
=> Hotfix PageHeader Styles

.eslintrc.json, src/Enums.js, src/PageContainer.js, src/PageContent/AssignVolunteers/AssignVolunteers.css, src/PageContent/AssignVolunteers/ConfirmationCard.css, src/PageContent/AssignVolunteers/ConfirmationCard.js, src/PageContent/Directory/Directory.css, src/PageContent/Directory/DirectoryCard.js, src/PageContent/Directory/DirectoryFilter.js, src/PageContent/Directory/DirectoryPage.js, src/PageContent/Directory/info.txt, src/PageContent/FoodLogs/FoodLogItem.css, src/PageContent/FoodLogs/FoodLogsContainer.css, src/PageContent/Settings/MemberAccount.js, src/PageContent/Settings/SCSettings0.css, src/PageLayout/Notification/Popup.css, src/PageLayout/PageHeader.css
various css changes to make it look like prod again
created pickups to see changes in confirm dialogs, open calendar events, etc.
=> Hotfix dev css

.travis.yml, package-lock.json, package.json, src/App.js
Checked banner on mobile. Banner does not appear on mobile deliveries, which is good. 
Changed wording of the banner if the browser is too small.
Opened different size browsers 😬
=> *hotfix* site wide warning banner

package-lock.json, src/PageContent/AssignVolunteers/AssignOption.js, src/PageContent/AssignVolunteers/AssignVolunteers.css, src/PageContent/AssignVolunteers/AssignVolunteersIndex.css, src/PageContent/AssignVolunteers/AssignVolunteersIndex.js, src/registerServiceWorker.js
Still have to fix a small bug with copying link to clipboard button and add a hover effect to the cards, but otherwise everything else is pretty much done.
Just a heads up, there's some errors with Travis and how I formatted my code using Prettier, might need to update that or Prettier but either way works.
Trello: https://www.figma.com/file/0S0hMjYPnzhAvhnddxgEgGud/Food-Waste-DRG-Revision-3?node-id=1%3A3
Updated the Assign Volunteers page to bring it closer to the design spec and added some of my own designs.
Start importing the css file and using CSS modules, SASS, and proptypes.
=> [Hotfix] Assign Volunteers UI Improvements

src/Map/Map.js
Quick fix so that map displays the correct visual in Settings.
<b>Changes: </b> <br>
- `src/Map/Map.js`
- Passed in GoogleMap_API_KEY to fromAddress function (line 44 of Map.js)
<b>Tests</b>
- Console.log statements to make sure that response function was being executed, not error.
=> Map Display

src/SignUpIn/SignIn.js, src/SignUpIn/SignUpIn.css
sends a password reset to the provided user email. 
**List of Changes** 
- Added "forgot password" button to sign in page. 
- created form in `signIn.js` for forgot password
- added forgot password email reset to `signIn.js`
**Tests** 
Made a Donating Group account with my personal email and tried out this feature. I reset my password and tried to log in with the old one but could only log in with the new one that I made through the reset email I received.
=> Feature Send Password Reset

src/PageContent/AssignVolunteers/AssignOption.js, src/PageContent/AssignVolunteers/AssignVolunteers.css, src/PageContent/AssignVolunteers/AssignVolunteersController.js, src/PageContent/AssignVolunteers/Edit.js
Summary: Now 1 OR 2 volunteers can be assigned to a delivery. 
**Changes**
-`src/PageContent/AssignVolunteers/Edit.js` - made form dynamic by creating a numVolunteers element to keep track of the state of the form. Also added a button that says "Add Second Volunteer" or "Remove Second Volunteer" depending on how many forms are up.
- `src/PageContent/AssignVolunteers/AssignVolunteers.css` Added in styling for add-button.
**Testing**
Went through process of assigning volunteers to make sure everything still runs smoothly.
=> Hotfix assign volunteers

src/PageContent/FoodLogs/FoodLogsContainer.css, src/PageContent/FoodLogs/FoodLogsContainer.js
Added a "Loading..." message to the top of the Food Logs tab
**Changes**
- `src/PageContent/FoodLogs/FoodLogsContainer.js` - Added a "isLoading" state variable to track whether page is loaded or not
- Conditional rendering dependent on isLoading value
- `src/PageContent/FoodLogs/FoodLogsContainer.css` styling for "Loading..." (just margining)
**Tests**
- Turned off Wifi and checked to see if Loading message appeared.
- Compared it to the "Loading..." message that appears on the Assign Volunteers page to make sure they look the same
- test with slow wifi to make sure it disappears when page is loaded.
=> Feature - Food Logs Loading Message

src/App.css, src/App.js
**Changes**
- `App.js` - changed blank page displayed while waiting for authentication to say "Loading..."
- `App.css` - added style for Loading message
=> loading message while waiting for authentication
